### ISSUE TITLE
only show as notification and blank space?

### ISSUE THREAD

**Issue by KairuiLiu** [fossfreedom/indicator-sysmonitor#102]

**Comment by KairuiLiu** [comment]
like this I use manjaro20.2 kde desptop

it only appery on System tray and i must hover on it it show the info... I want it show on the top bar

![image](https://user-images.githubusercontent.com/25458969/103847340-f943e100-50da-11eb-8078-88854f421361.png)


thanks!

**Comment by fossfreedom** [comment]
Sounds like a question for manjaro's application indicator implemention.

All app indicator implementations that I'm aware of place the text part of the appindicator next to the invisible icon - not as a popup as shown.

**Comment by will-molloy** [comment]
@KairuiLiu did you get it working?

**Comment by KairuiLiu** [comment]
> @KairuiLiu did you get it working?

No, I don't use KDE anymore.

**Comment by KairuiLiu** [comment]
> @KairuiLiu did you get it working?

No, I don't use KDE anymore.
