### ISSUE TITLE
Unable to locate package: indicator-sysmonitor 

### ISSUE THREAD

**Issue by ZhongQingliang** [fossfreedom/indicator-sysmonitor#103]
Recently I have tried to install the sysmonitor on Ubuntu16.04 platform via PPA source. But it failed to locate the package. When I  did a zsh-tab to list indicator-* packages, the "indicator-sysmonitor" did not show up. Is the PPA source invalid now?

![image](https://user-images.githubusercontent.com/48121259/104730361-df5a6c00-5774-11eb-8f00-14f042a6816c.png)

![image](https://user-images.githubusercontent.com/48121259/104730656-690a3980-5775-11eb-8149-ad932a6d6e99.png)

**Comment by fossfreedom** [comment]
yeah - 16.04 is no-longer supported.
