### ISSUE TITLE
[Question] Will indicator-sysmonitor work with linux mint?

### ISSUE THREAD

**Issue by fightthepower** [fossfreedom/indicator-sysmonitor#105]
Sorry for asking this question here but I don't know where-else should I ask this query. I am using this app in my ubuntu desktop and i love it. I am planning to uninstall my current ubuntu from desktop and reinstall it with new linux mint + kate (Cinnamon and xfce are optional). Before installing linux mint, I want to ask whether `indicator-sysmonitor` will work on mint+kate or do we have install any additional apps. If possible can you please provide a list of os's (ubuntu flavour as well as non ubuntu distros) which supports `indicator-sysmonitor`

**Comment by fossfreedom** [comment]
As long as the desktop environment supports appindicators either natively or via a third-party applet/extension, then indicator-sysmonitor "should-just-work <sup>(TM)</sup>"
