### ISSUE TITLE
can we format the out put of {net} and other things?

### ISSUE THREAD

**Issue by Fmajor** [fossfreedom/indicator-sysmonitor#11]
for example, I'd like the {net} output be like "%3d/%2s", then the output will not be a dangler no matter what the digital and the unit is.
I find the output a little annoying when it change its length all the time, along with the icon before it.

**Comment by fossfreedom** [comment]
looks like there is a bug in Unity App Indicator that makes this impossible to-do with the default API

 - https://bugs.launchpad.net/indicator-application/+bug/1310386

**Comment by fossfreedom** [comment]
close in favour of #9
