### ISSUE TITLE
indicator-sysmonitor crashed with FileNotFoundError in _execute_child(): [Errno 2] No such file or directory: 'nvidia-smi'

### ISSUE THREAD

**Issue by issemLenoil** [fossfreedom/indicator-sysmonitor#122]
I uninstalled nvidia drivers and my indicator-sysmonitor stopped working.

The reason is, that my configuration was using GPU sensors.
To solve the problem, probably I need change configuration of indicator-sysmonitor (remove nvgpu sensor from my view configuration).
How can I do it, without starting indicator-sysmonitor? My indicator-sysmonitor does not start now, so it is not possible to do it via GUI.

**Comment by fossfreedom** [comment]
indicator sysmonitor stores stuff in two locations - you can remove those before starting to reset things

./sensors.py:52: SETTINGS_FILE = os.getenv("HOME") + '/.indicator-sysmonitor.json'

./preferences.py:222: SETTINGS_FILE = os.getenv("HOME") + '/.cache/indicator-sysmonitor/preferences.json'
