### ISSUE TITLE
ubuntu22.04 fail

### ISSUE THREAD

**Issue by zhang7249** [fossfreedom/indicator-sysmonitor#124]
INFO:root:start
INFO:root:Menu shown
INFO:root:Fetcher started

(indicator-sysmonitor:48113): Gdk-CRITICAL **: 14:54:27.224: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

**Comment by fossfreedom** [comment]
"ubuntu22.04 fail" - what does this mean?  What is happening?  I presume this is gnome-shell with the appindicator extension installed and activated?
