### ISSUE TITLE
Not support Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by ntbowen** [fossfreedom/indicator-sysmonitor#129]
It can run on Ubuntu 24.04 LTS but seems some issues on display, nothing can be shown on topbar.

**Comment by fossfreedom** [comment]
Please give details of your setup - have you got the appindicator extension installed?  Are other appindicators being displayed correctly?  Any messages in journalctl after running with indicator-sysmonitor?

**Comment by yangliuan** [comment]
on ubuntu24.04 
indicator-sysmonitor
/usr/lib/indicator-sysmonitor/sensors.py:100: SyntaxWarning: invalid escape sequence '\A'
  reg = "\A({})\Z".format(reg)
/usr/lib/indicator-sysmonitor/sensors.py:402: SyntaxWarning: invalid escape sequence '\d'
  name = 'cpu\d*'
/usr/lib/indicator-sysmonitor/sensors.py:404: SyntaxWarning: invalid escape sequence '\A'
  cpus = re.compile("\Acpu\d*\Z")
/usr/lib/indicator-sysmonitor/sensors.py:467: SyntaxWarning: invalid escape sequence '\.'
  release = re.split('\.', platform.release())
/usr/lib/indicator-sysmonitor/sensors.py:551: SyntaxWarning: invalid escape sequence '\d'
  name = 'bat\d*'
/usr/lib/indicator-sysmonitor/sensors.py:553: SyntaxWarning: invalid escape sequence '\A'
  bat = re.compile("\Abat\d*\Z")
INFO:root:start
INFO:root:Menu shown
INFO:root:Fetcher started

**Comment by yangliuan** [comment]
after fix SyntaxWarning nothing can be shown on topbar.

**Comment by yangliuan** [comment]
![Uploading VirtualBox_ubuntu2404_22_05_2024_10_41_29.png…]()

**Comment by fossfreedom** [comment]
Hmm...thx

Immediate thoughts that this is due to python 12 issues around the re module

Needs investigating.

**Comment by yangliuan** [comment]
> Hmm...thx 嗯。。。感谢
> 
> Immediate thoughts that this is due to python 12 issues around the re module立即想到这是由于 re 模块周围的 python 12 问题
> 
> Needs investigating. 需要调查。
> 
> Edit 编辑
> 
> Probably this https://stackoverflow.com/questions/50504500/deprecationwarning-invalid-escape-sequence-what-to-use-instead-of-d大概是这个 https://stackoverflow.com/questions/50504500/deprecationwarning-invalid-escape-sequence-what-to-use-instead-of-d

Sure,I used ChatGPT to fix this syntax waring, but after running it again, the top bar still does not display anything.

**Comment by fossfreedom** [comment]
> Sure,I used ChatGPT to fix this syntax waring,

What was its suggested fix?

**Comment by yangliuan** [comment]
> > Sure,I used ChatGPT to fix this syntax waring,当然，我用ChatGPT解决了这个语法问题，
> 
> What was its suggested fix?它建议的修复方法是什么？
sensors.py
100：reg = r"\A({})\Z".format(reg)
402：name = r'cpu\d*'
404：cpus = re.compile(r"\Acpu\d*\Z")
467：release = re.split(r'\.', platform.release())
551：name = r'bat\d*'
553：bat = re.compile(r"\Abat\d*\Z")

**Comment by fossfreedom** [comment]
Looks like the gnome-shell appindicator extension doesnt allow labels to be displayed - only icons.

**Comment by Bernmeister** [comment]
> Looks like the gnome-shell appindicator extension doesnt allow labels to be displayed - only icons.

Not so, I've have been testing my own appindicators on Ubuntu 24.04 and icons/labels work fine.

**Comment by fossfreedom** [comment]
Please give me a link to one of your python appindicators working on gnome-shell. Let me compare and contrast.

**Comment by Bernmeister** [comment]
Hosted on [Launchpad](https://launchpad.net/~thebernmeister/+archive/ubuntu/ppa):

The [deb file](https://launchpad.net/~thebernmeister/+archive/ubuntu/ppa/+files/indicator-punycode_1.0.15-1_all.deb)

The [orig.tar.gz](https://launchpad.net/~thebernmeister/+archive/ubuntu/ppa/+sourcefiles/indicator-punycode/1.0.15-1/indicator-punycode_1.0.15.orig.tar.gz)

**Comment by fossfreedom** [comment]
cheers - which one displays a label alongside the "..." icon?  I've tried
both stardate and punycode and both just show "..." as an icon.

**Comment by fossfreedom** [comment]
ok - thats quite a bit of time wasted :(

The set_label issue is a bug under gnome-shell - it is going through the SRU process

https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-appindicator/+bug/2059818

I can confirm the noble-proposed package together with the git master version of indicator-sysmonitor displays correctly.
