### ISSUE TITLE
I updated my library and the software kept crashing after restarting.

### ISSUE THREAD

**Issue by ZJDATY** [fossfreedom/indicator-sysmonitor#131]
This morning, I updated my library and the software kept crashing after restarting.

### /var/log/apt/history.log
```
Start-Date: 2024-05-30  10:12:40
Commandline: aptdaemon role='role-commit-packages' sender=':1.596'
Upgrade: libtss2-tcti-cmd0:amd64 (3.2.0-1ubuntu1, 3.2.0-1ubuntu1.1), gstreamer1.0-gl:amd64 (1.20.1-1ubuntu0.1, 1.20.1-1ubuntu0.2), libtss2-tcti-device0:amd64 (3.2.0-1ubuntu1, 3.2.0-1ubuntu1.1), libtss2-tcti-swtpm0:amd64 (3.2.0-1ubuntu1, 3.2.0-1ubuntu1.1), libgstreamer-gl1.0-0:amd64 (1.20.1-1ubuntu0.1, 1.20.1-1ubuntu0.2), gstreamer1.0-plugins-base-apps:amd64 (1.20.1-1ubuntu0.1, 1.20.1-1ubuntu0.2), libtss2-mu0:amd64 (3.2.0-1ubuntu1, 3.2.0-1ubuntu1.1), gstreamer1.0-alsa:amd64 (1.20.1-1ubuntu0.1, 1.20.1-1ubuntu0.2), indicator-sysmonitor:amd64 (0.9.0ubuntu1~focal, 0.10.0-0ubuntu1~jammy), libc6:amd64 (2.35-0ubuntu3.7, 2.35-0ubuntu3.8), libc6:i386 (2.35-0ubuntu3.7, 2.35-0ubuntu3.8), locales:amd64 (2.35-0ubuntu3.7, 2.35-0ubuntu3.8), gstreamer1.0-x:amd64 (1.20.1-1ubuntu0.1, 1.20.1-1ubuntu0.2), gstreamer1.0-plugins-base:amd64 (1.20.1-1ubuntu0.1, 1.20.1-1ubuntu0.2), libtss2-tcti-mssim0:amd64 (3.2.0-1ubuntu1, 3.2.0-1ubuntu1.1), libc-dev-bin:amd64 (2.35-0ubuntu3.7, 2.35-0ubuntu3.8), libtss2-sys1:amd64 (3.2.0-1ubuntu1, 3.2.0-1ubuntu1.1), libc-bin:amd64 (2.35-0ubuntu3.7, 2.35-0ubuntu3.8), libc-devtools:amd64 (2.35-0ubuntu3.7, 2.35-0ubuntu3.8), libc6-dbg:amd64 (2.35-0ubuntu3.7, 2.35-0ubuntu3.8), libc6-dev:amd64 (2.35-0ubuntu3.7, 2.35-0ubuntu3.8), libtss2-esys-3.0.2-0:amd64 (3.2.0-1ubuntu1, 3.2.0-1ubuntu1.1), libgstreamer-plugins-base1.0-0:amd64 (1.20.1-1ubuntu0.1, 1.20.1-1ubuntu0.2), intel-microcode:amd64 (3.20231114.0ubuntu0.22.04.1, 3.20240514.0ubuntu0.22.04.1)
End-Date: 2024-05-30  10:13:16
```

### Error log

![image](https://github.com/fossfreedom/indicator-sysmonitor/assets/29767049/60584a7b-da28-4c6b-b22b-49526bfdac4b)
### Addendum: 
I updated using PPA and only then did I notice that the indicator sysmonitor was just updated yesterday. I should have been using the previous version before this update. This issue may be caused by updating to 0.10.0.
`sudo add-apt-repository ppa:fossfreedom/indicator-sysmonitor`

**Comment by ZJDATY** [comment]
@fossfreedom I manually installed version 0.5.0, but it still crashes. The error code is the same as "KeyError nvgputemp".Have the names of keywords"nvgputemp" changed in the libraries I updated?

**Comment by xpww** [comment]
I have the same problem, and it bothers me...

**Comment by ZJDATY** [comment]
> I have the same problem, and it bothers me...

I hope the official takes this issue seriously

**Comment by 12189108** [comment]
I have submitted a PR and am waiting for it to be merged. You can also manually modify line 112 of `/usr/lib/indicator-sysmonitor/sensors.py` by changing `if sensor.check(name) is not None` to `if sensor.check(name)` to resolve the issue.

**Comment by fossfreedom** [comment]
The ppa has now been updated. Thx.

**Comment by ZJDATY** [comment]
> The ppa has now been updated. Thx.

I have installed a new version, and it does not crash, but the temperature of the nvgpu has always been 0. Can you take a look? My configuration code is as follows:
`{net} cpu: {cpu} mem: {mem} gpu:{nvgpu} cpu:{cputemp} gpu:{nvgputemp}`
![image](https://github.com/fossfreedom/indicator-sysmonitor/assets/29767049/9c83171f-08d2-49d5-81bc-c329deb761ac)
![image](https://github.com/fossfreedom/indicator-sysmonitor/assets/29767049/41bf3f16-65fd-4967-8846-8df137b2d140)

**Comment by fossfreedom** [comment]
My bad - forgot to remove this debugging statement.  I'll patch this soonish.

a15cdaa5578f698482252622d441e4fd55cc8f6d

**Comment by ZJDATY** [comment]
> My bad - forgot to remove this debugging statement. I'll patch this soonish.
> 
> [a15cdaa](https://github.com/fossfreedom/indicator-sysmonitor/commit/a15cdaa5578f698482252622d441e4fd55cc8f6d)

Thank you for discovering the issue in a timely manner. I have another question, has the version number not been updated here?
![截图 2024-06-04 16-10-33](https://github.com/fossfreedom/indicator-sysmonitor/assets/29767049/0fa37724-62e6-4b2d-b323-eb9914a8907a)

**Comment by fossfreedom** [comment]
f02f32e4ca3bfa5f2ff3effc43f100aaaa2ae7e1
