### ISSUE TITLE
Doesn't start on Ubuntu 15.04

### ISSUE THREAD

**Issue by janot** [fossfreedom/indicator-sysmonitor#17]
indicator-sysmonitor stopped launching after upgrading from 14.10 to 15.04

janot@ACER:~/Downloads/indicator-sysmonitor$ indicator-sysmonitor
Traceback (most recent call last):
  File "/usr/bin/indicator-sysmonitor", line 32, in <module>
    logging.basicConfig(file=sys.stderr, level=logging.INFO)
  File "/usr/lib/python3.4/logging/__init__.py", line 1760, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): file
janot@ACER:~/Downloads/indicator-sysmonitor$

**Comment by fossfreedom** [comment]
should be fixed now.  Thanks.
