### ISSUE TITLE
v0.6 doesn't start in Ubuntu 15.04

### ISSUE THREAD

**Issue by janot** [fossfreedom/indicator-sysmonitor#18]
janot@ACER:~/Downloads/indicator-sysmonitor$ indicator-sysmonitor
Traceback (most recent call last):
  File "/usr/bin/indicator-sysmonitor", line 23, in <module>
    from preferences import Preferences
ImportError: No module named 'preferences'

**Comment by fossfreedom** [comment]
thanks for reporting this.  Should be resolved now.
