### ISSUE TITLE
Custom command not working 

### ISSUE THREAD

**Issue by potholiday** [fossfreedom/indicator-sysmonitor#20]
I uses custom commands to run in indicator-sysmonitor. I am able to execute simple cusom commands like

sensor: simple
description: Simple command
command: echo simple

but when i tried save complex command like this

sensor: complex
description: complex command
command: id=45; if [ $id -ge 30 ]; then echo Successful; echo $id; else echo fail; echo $id; fi

its showing this error 

"Sensor not supported" error

any idea how to solve this error

**Comment by fossfreedom** [comment]
I'm not at my ubuntu terminal at the moment ... but the output of the bash script must be only one echo statement.  You have two here.  You need to concatenate the two output strings.

**Comment by potholiday** [comment]
Thank fossfreedom for quick reply and sorry for this late post. I was able to work out that problem. Is it possible to execute a zenity or a notify command on sysmonitor-indicator 
eg:
zenity --warning --text "This will kill, are you sure?";echo $id 
or
notify-send "Successful" "echo $id"

**Comment by fossfreedom** [comment]
That is not something I've tried.  In theory it should work - indicator-sysmonitor is only looking for the output of the bash script.

So in theory - the bash script could run anything you like ... as long as the end result is one line of text.

Thus - as long as notify-send doesnt output something to the shell then all will be OK.  If it does you may be required to pipe the result into >dev/null or something similar.

**Comment by potholiday** [comment]
Thanks fossfreedom for the information and also i would like to thank you for giving us this awesome software. Even a novice like me can make my own custom indicator using your software:).
