### ISSUE TITLE
"No output" warning in a successfully executed bash code

### ISSUE THREAD

**Issue by potholiday** [fossfreedom/indicator-sysmonitor#21]
Hello again fossfreedom,
I have this issue (a minor one) when running a bash script with out any print output, indicator panel shows this error "(no output)" other than that the command is executing successfully.

For example

Sensor: {ex}
command: id=45; if [ $id -ge 30 ]; then echo "";  else echo ""; fi

shows this error in panel "(no output)"

How to remove "(no output)" error from panel for the executing bash code

**Comment by fossfreedom** [comment]
how about just echo a space rather than an empty string i.e.

    command: id=45; if [ $id -ge 30 ]; then echo " "; else echo " "; fi

**Comment by potholiday** [comment]
Nothing, still showing the same error "(no output)"

**Comment by fossfreedom** [comment]
Hmm ... Line 280 of sensors.py is deliberately stripping spaces from the returned results.  I think this a good idea. What you probably want is another Sensor that does not output anything.

Happy to receive patches to add this capability.

Until then suggest remove the .strip() command and this will do what you want.

**Comment by potholiday** [comment]
Thanks foss freedom for the quick reply and fix
