### ISSUE TITLE
How to make indicator-sysmonitor as a default indicator

### ISSUE THREAD

**Issue by potholiday** [fossfreedom/indicator-sysmonitor#22]
The ubuntu 14.04 currently have at the top right corner these indicators shutdown,lock buttom, calender time details, battery details, Input format (english) as the default indicators. is it possible to make indicator-sysmonitor as one of those default indicators. Now what happens is only when we logged into a computer, indicator-sysmonitor will be shown and when you log out or lock our computer indicator-sysmonitor  will automatically exit from panel. I know from experience in  locked computers indicator-sysmonitor works in the background but will not show in the panel. I have some stats (include cpu,mem and some custom) which i want to see when i lock my computer.

can it be done?

cheers
potholiday

**Comment by fossfreedom** [comment]
That is an excellent question ... which I dont have an answer.

My suggestion is to raise this on Ask Ubuntu.  I suspect someone there will know the answer.

**Comment by potholiday** [comment]
Thanks foss freedom.. i will ask this question in askubuntu

**Comment by fossfreedom** [comment]
@potholiday 

 - does this Ask Ubuntu Q&A help here?

 http://askubuntu.com/questions/604564/how-do-i-add-or-manipulate-application-system-indicators-in-the-login-screen

**Comment by potholiday** [comment]
@fossfreedom 
Hey thanks for keeping in touch. I have only a basic understanding of linux architecture and for me both answers doesn't make any sense. I follwed the highly voted answer 

`sudo nano /usr/share/unity/indicators/com.canonical.indicator.keyboard`
```
[Indicator Service]
Name=indicator-keyboard
ObjectPath=/com/canonical/indicator/keyboard
Position=80

[desktop]
ObjectPath=/com/canonical/indicator/keyboard/desktop

#[desktop_greeter]
#ObjectPath=/com/canonical/indicator/keyboard/desktop_greeter

#[desktop_lockscreen]
#ObjectPath=/com/canonical/indicator/keyboard/desktop_lockscreen

[ubiquity]
ObjectPath=/com/canonical/indicator/keyboard/desktop
```
now how should i add **indicator-sysmonitor** to it

**Comment by fossfreedom** [comment]
not sure - if I get some time I'll have a look - let me know if you managed to find the answer in the interim.

**Comment by chintan-sh** [comment]
Anyone got the solution?

**Comment by fossfreedom** [comment]
@potholiday - I've added a bounty to your question on Ask Ubuntu.  Lets hope we get a good answer!

**Comment by fossfreedom** [comment]
closing this - there is now a solution for this on Ask Ubuntu.

http://askubuntu.com/questions/628720/how-to-make-indicator-sysmonitor-as-a-default-indicator-on-the-login-screen

**Comment by potholiday** [comment]
@fossfreedom sorry been away from my system.. thanks for starting the bounty and solving the problem
