### ISSUE TITLE
Online Checker

### ISSUE THREAD

**Issue by Mannshoch** [fossfreedom/indicator-sysmonitor#29]
Hi

I'm looking for a tool hwo is able to show me a List of IP and their current Online status.

Could I somehow get this with your tool?
##

**Comment by fossfreedom** [comment]
The indicator as currently written can write a text string to the panel via a bash script.

So you could write a bash script that looked at each IP address - ping that IP address and return a "U" for Up and "D" for down - concatenate each result and display the result.

Probably better though to change the indicator to have the ability to return the result of each IP address and display both the IP address and that status as a menu option that you access when clicking the indicator icon.

So - with a bit of coding you could achieve this - but as currently written, the indicator will not display lists of stuff.
