### ISSUE TITLE
Blank space

### ISSUE THREAD

**Issue by justintv90** [fossfreedom/indicator-sysmonitor#31]
There is a blank space in the first offest of this indicator like the screenshot, how do i fix it ? Please help me. Thanks alot

http://i.imgur.com/HTaNY9L.png
##

**Comment by fossfreedom** [comment]
hmm - have you been fiddling with the spacing between indicators?  if so how did you do this?

in the preferences are you sure you dont have a space character at the beginning of the list of sensors being run?

**Comment by justintv90** [comment]
I havent modified anything in indicator system file and there wasnt any blank space character at the list. My os is linux mint xfce 17.2, any solution for this situation ?

**Comment by fossfreedom** [comment]
to provide a solution you first have to reproduce this.

This doesnt occur with Ubuntu Unity which I use.  XFCE/Mint must be interpreting application indicators is a different manner from Ubuntu Unity.

You can look at the code itself - indicator-sysmonitor is the file and have a play to see if you can change the behaviour.

Speculating - maybe Mint is expecting an indicator to always have an icon - that looks from your picture as to the space where an icon would be located.  This indicator does have an icon - but its sized to be a hidden 1px size.  Maybe Mint is ignoring this for some reason.

**Comment by fossfreedom** [comment]
XFCE now shows an icon instead of a blank space.
