### ISSUE TITLE
support displaying icons

### ISSUE THREAD

**Issue by fossfreedom** [fossfreedom/indicator-sysmonitor#32]
At the moment the indicator just displays the output of a string.

If a sensor itself outputs "USE_ICON:full_path_to.svg" we should add/change the icon
##

**Comment by chintan-sh** [comment]
Hey @fossfreedom, is it mandatory to load '.svg' file? I have a png however it shows 'no output' instead of displayin the icon.

**Comment by fossfreedom** [comment]
I may  be wrong - but I think indicators only support .svg icons

**Comment by chintan-sh** [comment]
Still cant make it work, here's what i did "USE_ICON:/home/chintan/Pictures/Flags/png/in.svg" and when I test it, it displays (no output).. cant tell what am I doing wrong.

**Comment by fossfreedom** [comment]
dropbox your script file - let me have a look

**Comment by pawandubey** [comment]
@fossfreedom Is there an example script for this use case?
