### ISSUE TITLE
Rather talkative log

### ISSUE THREAD

**Issue by hsasshofer** [fossfreedom/indicator-sysmonitor#34]
gnome-session is quite talkative in Ubuntu when using the online indicator, as `'if wget -O /dev/null google.com > /dev/null; then echo "☺"; else echo "☹"; fi'` will still output wget's actions, maybe adding the quiet option would be better `'if wget -qO /dev/null google.com > /dev/null; then echo "☺"; else echo "☹"; fi'`

**Comment by fossfreedom** [comment]
thanks - have added this.   Cheers for the report.
