### ISSUE TITLE
module 'psutil' has no attribute 'network_io_counters'

### ISSUE THREAD

**Issue by Polochamps** [fossfreedom/indicator-sysmonitor#40]
Ubuntu 16.04

This pops up " module 'psutil' has no attribute 'network_io_counters' " when I tried to add "net" on the output.

I also change xenial to wily just to install it - http://ppa.launchpad.net/fossfreedom...monitor/ubuntu wily main

**Comment by fossfreedom** [comment]
Thanks for raising the issue.

  according to the documentation (https://code.google.com/p/psutil/wiki/Documentation) "network_io_counters" has been replaced by "net_io_counters"

Can you have a look at sensors.py line 426 and seeing if substituting the new name for the old name works?

**Comment by Polochamps** [comment]
Thanks for the quick response.

Yes. It's finally working!

**Comment by fossfreedom** [comment]
ta :)
