### ISSUE TITLE
Doesn't work in Ubuntu 16.04

### ISSUE THREAD

**Issue by WLBI** [fossfreedom/indicator-sysmonitor#44]
From this website: https://launchpad.net/indicator-sysmonitor/ 
I installed the latest .deb package 
**indicator-sysmonitor_0.4.3_all.deb**
in Ubuntu 16.04 but the indicator dosn't work.
It looks like this:
http://fs5.directupload.net/images/160324/juccmbta.png
In the panel I get the output:
http://paste.ubuntu.com/15485733/

The Ubuntu team said I have to report the bug to you.

Thanks Alex

**Comment by fossfreedom** [comment]
??? launchpad.net/indicator-sysmonitor is not my project.

I've forked that because the original author stopped working on that years ago.

Suggest uninstall that version and install the version from my PPA here: https://launchpad.net/~fossfreedom/+archive/ubuntu/indicator-sysmonitor

**Comment by WLBI** [comment]
Hello Davidm

thanks for your reply!
I added your PPA to Ubuntu 15.10 and it works great there.
But in 16.04 I see the errors below, when starting in terminal.

I thought it's maybe the problem within 16.04, but the Ubuntu team said,
that I should contact the maintainer of the package.
For me this is the most important thing in Ubuntu. Without that I can't
see if there is any network activity, or if the connection stops.
Especially if I am using the mobile network.

Alex

===================================================================
alex@xc1706:~$ indicator-sysmonitor
sys:1: PyGIWarning: AppIndicator3 was imported without specifying a
version first. Use gi.require_version('AppIndicator3', '0.1') before
import to ensure that the right version gets loaded.
INFO:root:start
INFO:root:Menu shown
INFO:root:Fetcher started
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 633, in run
    data = self.fetch()
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 628, in fetch
    return self.mgr.get_results()
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 275, in get_results
    value = instance.get_value(sensor)
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 421, in get_value
    return self._fetch_net()
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 426, in _fetch_net
    for _, iostat in list(ps.network_io_counters(pernic=True).items()):
AttributeError: module 'psutil' has no attribute 'network_io_counters'

Traceback (most recent call last):
  File "/usr/bin/indicator-sysmonitor", line 253, in <module>
    app = IndicatorSysmonitor()
  File "/usr/bin/indicator-sysmonitor", line 100, in __init__
    self.load_settings()
  File "/usr/bin/indicator-sysmonitor", line 174, in load_settings
    self.update_indicator_guide()
  File "/usr/bin/indicator-sysmonitor", line 134, in update_indicator_guide
    guide = self.sensor_mgr.get_guide()
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 201, in get_guide
    data = self._fetcher.fetch()
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 628, in fetch
    return self.mgr.get_results()
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 275, in get_results
    value = instance.get_value(sensor)
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 421, in get_value
    return self._fetch_net()
  File "/usr/lib/indicator-sysmonitor/sensors.py", line 426, in _fetch_net
    for _, iostat in list(ps.network_io_counters(pernic=True).items()):
AttributeError: module 'psutil' has no attribute 'network_io_counters'








Am 24.03.2016 um 10:08 schrieb David Mohammed:

**Comment by fossfreedom** [comment]
ok your issue is this: https://github.com/fossfreedom/indicator-sysmonitor/issues/40

Please for the moment install the git version of the project.

I'll respin the PPA at some-point.  When done you can then remove the git version.

Let me know how you get on.

**Comment by wayneschuller** [comment]
I can confirm I had the same bug with the PPA version in 16.04. (bug was AttributeError etc for network speed)

However you are correct, the git version works fine.

I now have the numerical upload/download speeds on my top left corner and that makes me happy again. :)

I definitely suggest respinning the PPA asap.

**Comment by fossfreedom** [comment]
many thanks for the confirmation.  Will respin asap - got some higher budgie-remix issues first but I'll get around to this in the next few days hopefully.

**Comment by wayneschuller** [comment]
They really should put you into the ubuntu default package system.

Would love to just do: apt-get install blah

It is incredibly useful to be able to monitor your own numerical network speeds.

**Comment by WLBI** [comment]
Am 27.03.2016 um 13:16 schrieb Wayne Schuller:

> They really should put you into the ubuntu default package system.
>
> Would love to just do: apt-get install blah


Would love to just do: apt install blah

apt-get is quite old fashion. Since how many years it's already apt not
apt-get... I think since 12.04?

**Comment by fossfreedom** [comment]
ok - latest stuff uploaded to the repo now.
