### ISSUE TITLE
Can't test or save my Preferences

### ISSUE THREAD

**Issue by Invis1ble** [fossfreedom/indicator-sysmonitor#52]
When I press 'Test' button or 'Save' button the window with the following text appears:
> Error
> 'NoneType' object has no attribute 'match'

If you need more info please let me know.

**Comment by Invis1ble** [comment]
Looks like the problem was in `.indicator-sysmonitor.json` that left from the old version of `indicator-sysmonitor`. After deleting this file it works.

**Comment by fossfreedom** [comment]
ah .. thanks for the info.  very useful.
