### ISSUE TITLE
{net} option changes size constantly

### ISSUE THREAD

**Issue by arslan2012** [fossfreedom/indicator-sysmonitor#53]
while using {net} some times its 1/s sometimes its 10KB/s sometime its 100KB/s
which is causing the indicator changes size constantly and makes it painful to watch, is there some way to make it use a constant size? like i tried adding \t etc. but apparently it doesn't work.

**Comment by fossfreedom** [comment]
This is covered by #9 - use the override suggestion  in the readme to make sure the indicator always appears on the left side of all indicators.
