### ISSUE TITLE
Does not work in "System Tray" of lxpanel

### ISSUE THREAD

**Issue by sidosoft** [fossfreedom/indicator-sysmonitor#55]
Within lxpanel 0.8.2 (Lubuntu 16.04), the indicator-sysmonitor does not work correctly inside the "System Tray" plugin box -- a blank space is shown instead of the desired output. Other apps e.g. skype, indicator-cpufreq, nm-applet etc. display correctly. However, if instead of the "System Tray", the "Indicator Applets" is used, indicator-sysmonitor works fine (as a sanity check). Is it possible to fix it to make it cooperate with "System Tray"?
##

**Comment by fossfreedom** [comment]
This is designed for app indicator supported desktops hence why it works with the indicator applet.

If you look at the budgie file you can see how I adapted this for the panel based budgie desktop.

I expect you could do something similar for lxpanel.

Happy to accept patches I.e. a lxpanel type implementation

**Comment by Bernmeister** [comment]
@sidosoft I just tested the latest version of the indicator in Lubuntu 18.04 and all is good.  I have not tested with Lubuntu 16.04 but given it will be out of support in April of 2019, maybe give 18.04 a shot.
