### ISSUE TITLE
Ubuntu 16.04 - AttributeError: module 'psutil' has no attribute 'NUM_CPUS'

### ISSUE THREAD

**Issue by waiylgeek** [fossfreedom/indicator-sysmonitor#56]
Hello,

I get this error on Ubuntu 16.04: ```AttributeError: module 'psutil' has no attribute 'NUM_CPUS'```

**Comment by fossfreedom** [comment]
please start a terminal and type 

    python3

You should see the following:
    Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
    [GCC 5.3.1 20160330] on linux
    Type "help", "copyright", "credits" or "license" for more information.

Type:

    import psutil as ps

Type:

    ps.__version__

What do you see? - you should see '3.4.2'

**Comment by waiylgeek** [comment]
Yes indeed, I see '3.4.2'

**Comment by fossfreedom** [comment]
what version of indicator-sysmonitor are you using?

**Comment by waiylgeek** [comment]
the `indicator-sysmonitor --version` returns `indicator-sysmonitor 0.7.0~stable`

**Comment by fossfreedom** [comment]
the latest version is 0.8~development

Please use the PPA or install the latest from github.

https://launchpad.net/~fossfreedom/+archive/ubuntu/indicator-sysmonitor/+packages

**Comment by waiylgeek** [comment]
Fixed. Thanks

**Comment by waiylgeek** [comment]
Fixed. Thanks!
