### ISSUE TITLE
This applet will kill budgie interface

### ISSUE THREAD

**Issue by apolitech** [fossfreedom/indicator-sysmonitor#61]
*\* (budgie-panel:6765): WARNING **: PowerIndicator.vala:171: Unable to discover a battery

*\* (budgie-panel:6765): WARNING **: libsession.vala:67: Error registering with session manager: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client

(budgie-panel:6765): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(budgie-panel:6765): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(budgie-panel:6765): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(budgie-panel:6765): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(budgie-panel:6765): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(budgie-panel:6765): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
INFO:root:start
INFO:root:Menu shown
INFO:root:Fetcher started
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(budgie-panel:6765): Gdk-WARNING **: budgie-panel: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
##

**Comment by fossfreedom** [comment]
the above commit should fix this.
