### ISSUE TITLE
ImportError: cannot import name AppIndicator3, introspection typelib not found

### ISSUE THREAD

**Issue by hoseahsu** [fossfreedom/indicator-sysmonitor#62]
My system is ubuntu-gnome16.04, and the python3 was the default ptyhon edition. 

$ indicator-sysmonitor             
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 890, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/indicator-sysmonitor", line 20, in <module>
    from gi.repository import AppIndicator3 as appindicator
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 127, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name AppIndicator3, introspection typelib not found

**Comment by fossfreedom** [comment]
hmm - wonder why you dont have this standard ubuntu package

install this package http://packages.ubuntu.com/xenial/gir1.2-appindicator3-0.1

**Comment by hoseahsu** [comment]
Fixed. Thanks!
