### ISSUE TITLE
Battery sensor not working on Ubuntu 16.10

### ISSUE THREAD

**Issue by amalmurali47** [fossfreedom/indicator-sysmonitor#65]
![image](https://cloud.githubusercontent.com/assets/3582096/21608615/95479bbc-d1e3-11e6-81a1-5ee24e7fa4c0.png)

I've supplied the above input, but it just displays a popup saying 'bat0' and does nothing. I've confirmed that the path exists:

$ ls /sys/class/power_supply/
ADP0  BAT0

I've also tried the inputs 'bat', and other uppercase variations, but no luck with that. I'm sorry if I misunderstood the usage.

**Comment by fossfreedom** [comment]
k - most unusual - the code is expecting /sys/class/power_supply/BAT0/capacity 

Not sure why you have got "ADP0 "as a prefix - that is your issue.

Look at sensors.py - the battery code is in the BatSensor class.  Think need some sort of rejig to cope with finding "folders" that is prefixed rather than an explicit "BAT".

Happy to receive a PR to resolve.

**Comment by amalmurali47** [comment]
ADP0 as a prefix? You mean that isn't supposed to be there? And how would
one fix this? Could you be more detailed? I'll give it a go although Python
isn't exactly my fortè.

**Comment by danielmohr** [comment]
From what I read, ADP just displays the power adapter state itself. So you might be fine with 

> /sys/class/power_supply/BAT0/capacity

Like @fossfreedom already mentioned. The ADP class would state if the power adapter is online when I read this blog post correctly. https://tuxdiary.com/2015/09/14/power-battery-status/

**Comment by amalmurali47** [comment]
@fossfreedom, @danielmohr: Not really sure what all that was supposed to mean. Is this an issue with indicator-sysmonitor and can it be fixed? If so, how?

**Comment by fossfreedom** [comment]
@amalmurali47 have you got a "file" in /sys/class/power_supply/BAT0/capacity?

If yes - what value is contained in it?  That is the value that is displayed by indicator-sysmonitor

**Comment by amalmurali47** [comment]
@fossfreedom : Yes, it is a file. It contains the value "100" (battery is fully charged now).

How to make indicator-sysmonitor display this value? Is the input that I've shown in the screenshot above correct? Or do I need to make some modifications for it to output 100?

**Comment by fossfreedom** [comment]
@amalmurali47 

hmm - had a quick code review - havent had time to test though

line 446 in sensors.py looks like this

```
def check(self, sensor):
        if self.bat.match(sensor):
            bat_id = int(sensor[3:]) if len(sensor) > 3 else 0
            if not os.path.exists("/sys/class/power_supply/BAT{}".format(bat_id)):
                 raise ISMError(_("Invalid number returned for the Battery sensor."))
```

I suspect it is missing a "return True" statement out of the if self.bat.match(sensor) check ie.

```
def check(self, sensor):
        if self.bat.match(sensor):
            bat_id = int(sensor[3:]) if len(sensor) > 3 else 0
            if not os.path.exists("/sys/class/power_supply/BAT{}".format(bat_id)):
                  raise ISMError(_("Invalid number returned for the Battery sensor."))
                  return False
            return True
```

**Comment by fossfreedom** [comment]
ok - the above commit should fix this now.

**Comment by amalmurali47** [comment]
Awesome, thanks!
