### ISSUE TITLE
Ubuntu 16.10 fs sensor not supported

### ISSUE THREAD

**Issue by buzai** [fossfreedom/indicator-sysmonitor#67]
this is  my settings cpu: {cpu} mem: {mem} net:{net} hd:{fs}
but it tell me fs is not supported

**Comment by Bernmeister** [comment]
I think you want something like:

`free: {fs///home/buzai}`

Assuming your home directory is /home/buzai.

**Comment by buzai** [comment]
@Bernmeister 
Haha, yes, you are so clever, thank you
