### ISSUE TITLE
Feature request: Auto IP blocker sensor

### ISSUE THREAD

**Issue by ghost** [fossfreedom/indicator-sysmonitor#70]
I was searching trough python reddit and found this link https://www.reddit.com/r/Python/comments/665wfc/auto_ip_blocker_from_blocklistde_list/

An auto IP blocker sensor would be a good addition for indicator-sysmonitor

**Comment by Bernmeister** [comment]
@ghost I presume you want to run the script (or an amended version) from the reddit post (there seems to be an updated version on GitHub too).  If so, why not use create a new sensor and add your script to that?
