### ISSUE TITLE
gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0

### ISSUE THREAD

**Issue by arbach** [fossfreedom/indicator-sysmonitor#73]
getting 

(indicator-sysmonitor:14027): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

on 
Gtk.main()

ubuntu 16.04

dpkg -l | grep gtk 

ii  adapta-gtk-theme                            3.91.2.41-0ubuntu1~xenial1                   all          Adapta Gtk+ Theme
ii  apport-gtk                                  2.20.1-0ubuntu2.10                           all          GTK+ frontend for the apport crash report system
ii  apturl                                      0.5.2ubuntu11.1                              amd64        install packages using the apt protocol - GTK+ frontend
ii  clipit                                      1.4.2-1ubuntu1                               amd64        lightweight GTK+ clipboard manager
ii  gir1.2-gtk-3.0:amd64                        3.18.9-1ubuntu3.3                            amd64        GTK+ graphical user interface library -- gir bindings
ii  gir1.2-gtksource-3.0:amd64                  3.18.2-1                                     amd64        gir files for the GTK+ syntax highlighting widget
ii  gir1.2-javascriptcoregtk-3.0:amd64          2.4.11-0ubuntu0.1                            amd64        JavaScript engine library from WebKitGTK+ - GObject introspection data
ii  gir1.2-javascriptcoregtk-4.0:amd64          2.16.6-0ubuntu0.16.04.1                      amd64        JavaScript engine library from WebKitGTK+ - GObject introspection data
ii  gir1.2-webkit-3.0:amd64                     2.4.11-0ubuntu0.1                            amd64        Web content engine library for GTK+ - GObject introspection data
ii  gir1.2-webkit2-4.0:amd64                    2.16.6-0ubuntu0.16.04.1                      amd64        Web content engine library for GTK+ - GObject introspection data
ii  gnome-themes-standard:amd64                 3.18.0-2ubuntu1                              amd64        Adwaita GTK+ 2 theme — engine
ii  gnome-themes-standard-data                  3.18.0-2ubuntu1                              all          Adwaita GTK+ 2 theme — common files
ii  gtk2-engines-murrine:amd64                  0.98.2-0ubuntu2.2                            amd64        cairo-based gtk+-2.0 theme engine
ii  gtk2-engines-pixbuf:amd64                   2.24.30-1ubuntu1.16.04.2                     amd64        pixbuf-based theme for GTK+ 2.x
ii  ibus-gtk:amd64                              1.5.11-1ubuntu2                              amd64        Intelligent Input Bus - GTK+2 support
ii  ibus-gtk3:amd64                             1.5.11-1ubuntu2                              amd64        Intelligent Input Bus - GTK+3 support
ii  libavahi-ui-gtk3-0:amd64                    0.6.32~rc+dfsg-1ubuntu2                      amd64        Avahi GTK+ User interface library for GTK3
ii  libcanberra-gtk-module:amd64                0.30-2.1ubuntu1                              amd64        translates GTK+ widgets signals to event sounds
ii  libcanberra-gtk0:amd64                      0.30-2.1ubuntu1                              amd64        GTK+ helper for playing widget event sounds with libcanberra
ii  libcanberra-gtk3-0:amd64                    0.30-2.1ubuntu1                              amd64        GTK+ 3.0 helper for playing widget event sounds with libcanberra
ii  libcanberra-gtk3-module:amd64               0.30-2.1ubuntu1                              amd64        translates GTK3 widgets signals to event sounds
ii  libcheese-gtk25:amd64                       3.18.1-2ubuntu3                              amd64        tool to take pictures and videos from your webcam - widgets
ii  libclutter-gtk-1.0-0:amd64                  1.6.6-1                                      amd64        Open GL based interactive canvas library GTK+ widget
ii  libcolord-gtk1:amd64                        0.1.26-1                                     amd64        GTK+ convenience library for interacting with colord
ii  libdbusmenu-gtk3-4:amd64                    16.04.1+16.04.20160927-0ubuntu1              amd64        library for passing menus over DBus - GTK+ version
ii  libdbusmenu-gtk4:amd64                      16.04.1+16.04.20160927-0ubuntu1              amd64        library for passing menus over DBus - GTK+ version
ii  libevview3-3:amd64                          3.18.2-1ubuntu4.1                            amd64        Document (PostScript, PDF) rendering library - Gtk+ widgets
ii  libgoocanvas3:amd64                         1.0.0-1                                      amd64        canvas widget for GTK+ that uses the cairo 2D library
ii  libgtk-3-0:amd64                            3.18.9-1ubuntu3.3                            amd64        GTK+ graphical user interface library
ii  libgtk-3-bin                                3.18.9-1ubuntu3.3                            amd64        programs for the GTK+ graphical user interface library
ii  libgtk-3-common                             3.18.9-1ubuntu3.3                            all          common files for the GTK+ graphical user interface library
ii  libgtk2-appindicator-perl                   0.15-1build3                                 amd64        Perl bindings for libappindicator
ii  libgtk2-imageview-perl                      0.05-2build2                                 amd64        Perl bindings for the GtkImageView image viewer widget
ii  libgtk2-perl                                2:1.2498-1                                   amd64        Perl interface to the 2.x series of the Gimp Toolkit library
ii  libgtk2-unique-perl                         0.05-2ubuntu1                                amd64        module for single instance applications
ii  libgtk2.0-0:amd64                           2.24.30-1ubuntu1.16.04.2                     amd64        GTK+ graphical user interface library
ii  libgtk2.0-0:i386                            2.24.30-1ubuntu1.16.04.2                     i386         GTK+ graphical user interface library
ii  libgtk2.0-bin                               2.24.30-1ubuntu1.16.04.2                     amd64        programs for the GTK+ graphical user interface library
ii  libgtk2.0-common                            2.24.30-1ubuntu1.16.04.2                     all          common files for the GTK+ graphical user interface library
ii  libgtkglext1:amd64                          1.2.0-3.2fakesync1ubuntu1                    amd64        OpenGL Extension to GTK+ (shared libraries)
ii  libgtkimageview0                            1.6.4+dfsg-1                                 amd64        image viewer widget for GTK+
ii  libgtkmm-2.4-1v5:amd64                      1:2.24.4-2                                   amd64        C++ wrappers for GTK+ (shared libraries)
ii  libgtkmm-3.0-1v5:amd64                      3.18.0-1                                     amd64        C++ wrappers for GTK+ (shared libraries)
ii  libgtksourceview-3.0-1:amd64                3.18.2-1                                     amd64        shared libraries for the GTK+ syntax highlighting widget
ii  libgtksourceview-3.0-common                 3.18.2-1                                     all          common files for the GTK+ syntax highlighting widget
ii  libgtkspell3-3-0:amd64                      3.0.7-2                                      amd64        spell-checking addon for GTK+'s TextView widget
ii  libido3-0.1-0:amd64                         13.10.0+16.04.20161028-0ubuntu1              amd64        Shared library providing extra gtk menu items for display in
ii  libjavascriptcoregtk-1.0-0:amd64            2.4.11-0ubuntu0.1                            amd64        JavaScript engine library from WebKitGTK+
ii  libjavascriptcoregtk-3.0-0:amd64            2.4.11-0ubuntu0.1                            amd64        JavaScript engine library from WebKitGTK+
ii  libjavascriptcoregtk-4.0-18:amd64           2.16.6-0ubuntu0.16.04.1                      amd64        JavaScript engine library from WebKitGTK+
ii  libnm-gtk-common                            1.2.6-0ubuntu0.16.04.3                       all          library for wireless and mobile dialogs - common files
ii  libnm-gtk0:amd64                            1.2.6-0ubuntu0.16.04.3                       amd64        library for wireless and mobile dialogs (libnm-glib version)
ii  libreoffice-gtk                             1:5.1.6~rc2-0ubuntu1~xenial2                 amd64        office productivity suite -- GTK+ integration
ii  libtimezonemap-data                         0.4.5                                        all          GTK+3 timezone map widget - data files
ii  libtimezonemap1:amd64                       0.4.5                                        amd64        GTK+3 timezone map widget
ii  libunity-gtk2-parser0:amd64                 0.0.0+15.04.20150118-0ubuntu2                amd64        GtkMenuShell to GMenuModel parser
ii  libunity-gtk3-parser0:amd64                 0.0.0+15.04.20150118-0ubuntu2                amd64        GtkMenuShell to GMenuModel parser
ii  libvte-2.91-0:amd64                         0.42.5-1ubuntu1                              amd64        Terminal emulator widget for GTK+ 3.0 - runtime files
ii  libvte-2.91-common                          0.42.5-1ubuntu1                              all          Terminal emulator widget for GTK+ 3.0 - common files
ii  libwebkit2gtk-4.0-37:amd64                  2.16.6-0ubuntu0.16.04.1                      amd64        Web content engine library for GTK+
ii  libwebkit2gtk-4.0-37-gtk2:amd64             2.16.6-0ubuntu0.16.04.1                      amd64        Web content engine library for GTK+ - GTK+2 plugin process
ii  libwebkitgtk-1.0-0:amd64                    2.4.11-0ubuntu0.1                            amd64        Web content engine library for GTK+
ii  libwebkitgtk-1.0-common                     2.4.11-0ubuntu0.1                            all          Web content engine library for GTK+ - data files
ii  libwebkitgtk-3.0-0:amd64                    2.4.11-0ubuntu0.1                            amd64        Web content engine library for GTK+
ii  libwebkitgtk-3.0-common                     2.4.11-0ubuntu0.1                            all          Web content engine library for GTK+ - data files
ii  libwmf0.2-7-gtk                             0.2.8.4-10.5ubuntu1                          amd64        Windows metafile conversion library
ii  libwxgtk3.0-0v5:amd64                       3.0.2+dfsg-1.3ubuntu0.1                      amd64        wxWidgets Cross-platform C++ GUI toolkit (GTK+ runtime)
ii  lightdm-gtk-greeter                         2.0.1-2ubuntu4                               amd64        simple display manager (GTK+ greeter)
ii  lightdm-gtk-greeter-settings                1.2.1-0ubuntu1                               all          settings editor for the LightDM GTK+ Greeter
ii  metacity                                    1:3.18.7-0ubuntu0.3                          amd64        lightweight GTK+ window manager
ii  overlay-scrollbar-gtk2:amd64                0.2.17.1+16.04.20151117-0ubuntu1.16.04.1     amd64        GTK 2 module for overlay scrollbars
ii  python-aptdaemon.gtk3widgets                1.1.1+bzr982-0ubuntu14                       all          Python 2 GTK+ 3 widgets to run an aptdaemon client
ii  python-glade2                               2.24.0-4ubuntu1                              amd64        GTK+ bindings: Glade support
ii  python-gtk2                                 2.24.0-4ubuntu1                              amd64        Python bindings for the GTK+ widget set
ii  python3-aptdaemon.gtk3widgets               1.1.1+bzr982-0ubuntu14                       all          Python 3 GTK+ 3 widgets to run an aptdaemon client
ii  software-properties-gtk                     0.96.20.7                                    all          manage the repositories that you install software from (gtk)
ii  transmission-gtk                            2.84-3ubuntu3                                amd64        lightweight BitTorrent client (GTK+ interface)
ii  ubuntu-release-upgrader-gtk                 1:16.04.22                                   all          manage release upgrades
ii  unity-gtk-module-common                     0.0.0+15.04.20150118-0ubuntu2                all          Common files for GtkMenuShell D-Bus exporter
ii  unity-gtk2-module:amd64                     0.0.0+15.04.20150118-0ubuntu2                amd64        GtkMenuShell D-Bus exporter
ii  unity-gtk3-module:amd64                     0.0.0+15.04.20150118-0ubuntu2                amd64        GtkMenuShell D-Bus exporter
ii  usb-creator-gtk                             0.3.2                                        amd64        create a startup disk using a CD or disc image (for GNOME)
ii  vim-gtk                                     2:7.4.1689-3ubuntu1.2                        amd64        Vi IMproved - enhanced vi editor - with GTK2 GUI
ii  xbindkeys-config                            0.1.3-2ubuntu1                               amd64        an easy to use gtk program for configuring Xbindkeys
ii  xdg-user-dirs-gtk                           0.10-1ubuntu1                                amd64        tool to manage well known user directories (Gtk extension)

**Comment by fossfreedom** [comment]
16.04 is no longer supported
