### ISSUE TITLE
Can't install with ppa in ubuntu artful (17.10)

### ISSUE THREAD

**Issue by fedeviotti** [fossfreedom/indicator-sysmonitor#76]
Hello, I added the repository as follow

> sudo add-apt-repository ppa:fossfreedom/indicator-sysmonitor
> sudo apt-get update

but the indicator-sysmonitor is not available for Ubuntu Artful 17.10 when I type

> sudo apt-get install indicator-sysmonitor

Here the error log (when I do the update command)
Err:10 http://ppa.launchpad.net/fossfreedom/indicator-sysmonitor/ubuntu artful Release
  404  Not Found
Thanks!

**Comment by fossfreedom** [comment]
Should now be resolved. Thanks

**Comment by fedeviotti** [comment]
Now it works. Thanks!
