### ISSUE TITLE
html output on a custom scripts 

### ISSUE THREAD

**Issue by bmomani1** [fossfreedom/indicator-sysmonitor#79]
I have a script and I want to see its output 
the output its a colored text 
but it appears as raw HTML
![image](https://user-images.githubusercontent.com/31382267/34983577-b55a3f2a-fab6-11e7-8be3-14bd970a74ba.png)\
could you please consider displaying HTML too

**Comment by fossfreedom** [comment]
the appindicator uses the available API which only allows icons and plain text to  be displayed.

So at best the only way to-do what you want is to have some sort of routine that converts the html output to a .svg or .png that can be displayed.

I'm not going to create something like that myself but would certainly amenable for a PR to add that capability.
