### ISSUE TITLE
numbers will die, often without change

### ISSUE THREAD

**Issue by shoukailiang** [fossfreedom/indicator-sysmonitor#84]
ubuntu 18.04 ，numbers will die, often without change

**Comment by fossfreedom** [comment]
absolutely no idea what you mean by "numbers will die, often without change"

**Comment by fossfreedom** [comment]
Start indicator sysmonitor from a command line.

Any warnings or errors around the time the panel values stop changing?

**Comment by dewana-dewan** [comment]
Facing the same issue. Using Ubuntu 17.10.
@fossfreedom Tried starting this manually, no error/warning before the numbers freeze.
From what I could analyse, the sensor manager works fine but issues is with updating the label.

**Comment by secretxu** [comment]
t happened to me too.I run it on startup.
Ubuntu 18.04LTS.

**Comment by fossfreedom** [comment]
These issues are on GNOME Shell with the app indicator gnome-shell extension?

If this isn't reproducible on other desktop environments this sounds more like a problem with the gnome-shell extension.

**Comment by rwikdutta** [comment]
i was facing the same problem on Ubuntu 18.04 thus I ran the command from terminal....this was the result...
`tor
INFO:root:start
INFO:root:Menu shown
INFO:root:Fetcher started
Gtk-Message: 15:22:07.123: GtkDialog mapped without a transient parent. This is discouraged.

(indicator-sysmonitor:28334): Gdk-CRITICAL **: 16:08:09.576: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
`

**Comment by fossfreedom** [comment]
Since you are encountering this on standard Ubuntu and it doesn't affect budgie or unity I can only conclude that this is a bug with Ubuntu appindicator extension. Guessing there is some sort of issue with applets frequently changing its details within its extension.

Sorry... nothing I can do here. The appindicator works just fine in other appindicator implementations

**Comment by NickSto** [comment]
I'm also seeing the indicator die periodically on Ubuntu 18.04, but with different errors. Should I make a separate issue? (or multiple issues?)
These 3 runs stayed up for between 4 min and about an hour.
```
$ indicator-sysmonitor 
INFO:root:start
INFO:root:Menu shown
INFO:root:Fetcher started
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3: ../../src/xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
```
```
$ indicator-sysmonitor 
INFO:root:start
INFO:root:Menu shown
INFO:root:Fetcher started
Gdk-Message: 19:00:48.554: indicator-sysmonitor: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
```
```
$ indicator-sysmonitor 
INFO:root:start
INFO:root:Menu shown
INFO:root:Fetcher started

(indicator-sysmonitor:19121): Gdk-ERROR **: 22:30:29.404: The program 'indicator-sysmonitor' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 1505 error_code 2 request_code 18 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)
```

**Comment by fossfreedom** [comment]
Those are X-Server issues. Again, it does look like a buggy GNOME Shell appindicator extension.  As I said previously, the appindicator works just fine on Unity and Budgie - so there isn't much I can do here.

**Comment by NickSto** [comment]
Oh, okay. So this is where I should take the reports, then?
https://github.com/ubuntu/gnome-shell-extension-appindicator

**Comment by fossfreedom** [comment]
yes - that looks like the correct place.

**Comment by NickSto** [comment]
FYI, I've been doing some experiments, and it seems that it dies more often (but not exclusively) when I include a custom sensor that executes a bash script I wrote. Could this be caused by the bash script blocking for too long, or even dying?

**Comment by quique0194** [comment]
Any workaround or link to the issue report on gnome-shell?

**Comment by fossfreedom** [comment]
@quique0194 I've pulled in a tweak in this area from a fork that wasnt PR'd - hopefully this will resolve matters on GNOME Shell. Version has been bumped to v0.8.3
