### ISSUE TITLE
Are there any future plans to increase the efficency of indicator-sysmonitor?

### ISSUE THREAD

**Issue by ghost** [fossfreedom/indicator-sysmonitor#85]
HI there,
Because indicator-sysmonitor is written fully in python it has some inefficencies like this https://github.com/fossfreedom/indicator-sysmonitor/issues/68 . Are there any future plans to increase the efficency of indicator-sysmonitor? Say by rewriting whole indicator-sysmonitor with a compiler language such as C or converting python to cython scripts?

**Comment by fossfreedom** [comment]
No plans myself to-do this.  

I suppose byte compiling a system wide installation would improve matters - this will need a small change in the Makefile.

cpython sounds interesting  - happy to see a PR with a demonstration and figures to show how things improve.
