### ISSUE TITLE
Fahrenheit

### ISSUE THREAD

**Issue by ScottMccay** [fossfreedom/indicator-sysmonitor#88]
is it possible to display cpu temp in Fahrenheit ?

**Comment by fossfreedom** [comment]
It is displaying the value directly from the kernel or Nvidia which is in Celsius

The code in sensors.py will need to have a small tweak to look for a value added to the sensor e.g.

    cpu/f 

So add a check method to CPUTemp to understand if the first 3 letters is cpu

Then in the get_value method look to see if the last character is f and then return a Celsius to farenheighr conversion.

**Comment by sterno1966** [comment]
thank you

**Comment by fossfreedom** [comment]
As I said ... the code will need to be tweaked

**Comment by sterno1966** [comment]
ok

**Comment by fossfreedom** [comment]
Sorry - lots of other projects at the moment.

Pull Requests are always welcome from anyone.  Otherwise I get around to this eventually.

**Comment by sterno1966** [comment]
can you point me to a tut that will help me do it ?

**Comment by fossfreedom** [comment]
Its a python applet - so you need python coding knowledge

Execute ./indicator-sysmonitor from a terminal to see any coding issues whilst running.

Guidance for changing sensors.py I mentioned at the top of this thread.
