### ISSUE TITLE
CPU, MEM value freeze & doesn't change after some time. 

### ISSUE THREAD

**Issue by anburocky3** [fossfreedom/indicator-sysmonitor#94]
I'm using the following in-build commands `cpu: {cpu} mem: {mem} {upordown}` to display my data.
It works sometime, but most cases, the values doesn't change and it looks like freeze state.

The only way to make it again work is to re-run it .

Looks like a bug? Isn't it?

**Comment by fossfreedom** [comment]
what desktop environment are you using?

**Comment by anburocky3** [comment]
I'm currently using `Ubuntu 19.10`. But this problem exist on previous LTS version too.

**Comment by fossfreedom** [comment]
Your issue is a duplicate https://github.com/fossfreedom/indicator-sysmonitor/issues/84

And this is a bug with gnome-shell's appindicator extension - nothing to-do with this project.  It seems that the extension cannot cope with frequently changing labels and freezes.
