### ISSUE TITLE
GPU and GPU temperature do not work. There are no macros in the list.

### ISSUE THREAD

**Issue by ShapovalovIgor** [fossfreedom/indicator-sysmonitor#95]
Macros do not work {nvgpu}{nvgputemp}

Open windows {nvgpu} not supported.

https://github.com/fossfreedom/indicator-sysmonitor/commit/8e10edb18ce189c6940c2f7825083c8d7d88ded4

**Comment by ShapovalovIgor** [comment]
updated and earned scrip /usr/lib/indicator-sysmonitort/sensors.py

**Comment by fossfreedom** [comment]
What changes did you make? Can you do a pull request for the change please?
