### ISSUE TITLE
Title: Will you consider supporting linux mint20 Cinnamon

### ISSUE THREAD

**Issue by omaidb** [fossfreedom/indicator-sysmonitor#98]
标题：是否会考虑支持 linux mint20 Cinnamon

我在ubuntu16.04 下一直使用indicator-sysmonitor.git，这是一个非常令人喜欢的项目。因为不太喜欢ubuntu20.04，我更换linux mint20之后，第一件事情就是安装indicator-sysmonitor，编译没有报错，但是无法运行。。。。

I have been using indicator-sysmonitor.git under ubuntu16.04, which is a very interesting project. Because I don't like ubuntu20.04 very much, after I replaced linux mint20, the first thing I did was to install indicator-sysmonitor. The compilation did not report an error, but it couldn't run. . . .

**Comment by fossfreedom** [comment]
As long as cinnamon supports appindicators then I dont see any reason why it shouldn't work.

Start the indicator via a command line ... if there are any warnings or crashes then please copy paste the output here

**Comment by omaidb** [comment]
qiaofei@qiaofei-Alienware-15-R3:/usr/bin$ bash indicator-sysmonitor
indicator-sysmonitor: line 12: import: command not found
indicator-sysmonitor: line 13: import: command not found
indicator-sysmonitor: line 14: import: command not found
indicator-sysmonitor: line 15: import: command not found
from: can't read /var/mail/argparse
from: can't read /var/mail/gettext
from: can't read /var/mail/gettext
from: can't read /var/mail/threading
indicator-sysmonitor: line 21: import: command not found
indicator-sysmonitor: line 22: syntax error near unexpected token
`'AppIndicator3','
indicator-sysmonitor: line 22: `gi.require_version('AppIndicator3', '0.1')'
[image: image.png]



David Mohammed <notifications@github.com> 于2020年8月9日周日 下午9:05写道：

**Comment by fossfreedom** [comment]
Looks like you are missing this package

gir1.2-appindicator3-0.1

**Comment by omaidb** [comment]
I have checked the package dependencies, this package is in accordance with
the instructions of README.md, all the required dependencies are installed
[image: image.png]
[image: image.png]
生命狂想


David Mohammed <notifications@github.com> 于2020年8月9日周日 下午9:52写道：

> Looks like you are missing this package
>
> gir1.2-appindicator3-0.1
>

**Comment by fossfreedom** [comment]
Wait!

You are trying to run the indicator using bash.

Just  run

    indicator-sysmonitor

**Comment by omaidb** [comment]
Originally, the indicator-sysmonitor program icon appeared in the lower
right corner, but nothing appeared. . . . .
[image: image.png]
生命狂想


David Mohammed <notifications@github.com> 于2020年8月9日周日 下午10:47写道：

**Comment by fossfreedom** [comment]
I cant see the image you posted.

If there is no errors or warnings when you indicator-sysmonitor then this must be a problem with cinnamon's appindicator implementation.

This isn't something I can fix ... you need to contact your cinnamon appindicator maintainer  or use a desktop environment and distro that supports appindicators properly like Ubuntu Budgie

**Comment by omaidb** [comment]
I repeatedly confirmed that a black box appeared. . .
Hovering over will show the internet speed. But in ubuntu Unity 16.04 it
will continue to display the internet speed, which does not look normal now.
[image: image.png]
生命狂想


Jon Lee <omaidb@gmail.com> 于2020年8月9日周日 下午10:53写道：

**Comment by omaidb** [comment]
The network started to be abnormal. I may only be able to communicate with
you another day。
Thank you for your selfless help
生命狂想


Jon Lee <omaidb@gmail.com> 于2020年8月9日周日 下午10:58写道：

**Comment by fossfreedom** [comment]
Do check if the issue is due to the gtk theme you are using. I.e. try
different themes

**Comment by hunantangke** [comment]
@omaidb Hi. I have the same problem. Have you solved it？

**Comment by omaidb** [comment]
Not resolved
生命狂想


tangke <notifications@github.com> 于2020年8月18日周二 上午9:39写道：

**Comment by will-molloy** [comment]
I've also been using this app since ~2016 on Ubuntu and switched to Mint Cinnamon today.

The app installs and runs, but it only displays when I hover the blank icon in the bar:
![Screenshot from 2024-05-23 14-12-17](https://github.com/fossfreedom/indicator-sysmonitor/assets/18110897/a3fa07b1-3652-451e-9cef-4edad77c2512)

Anyone know how to fix this? I want it displayed IN the bar.
